#spring:
#  security:
#    oauth2:
#      client:
#
#        registration:
#          google:
#            client-name: ????
#            client-id: ????? ?? ?? ???
#            client-secret: ????? ?? ?? ????
#            redirect-uri: ???? ??? ???? ??? ?? URI
#            authorization-grant-type: ?? ??
#            scope: ??? ???? ??? ??? ??
#              - s
#          naver:
#            client-name: ????
#            client-id: ????? ?? ?? ???
#            client-secret: ????? ?? ?? ????
#            redirect-uri: ???? ??? ???? ??? ?? URI
#            authorization-grant-type: ?? ??
#            scope: ??? ???? ??? ??? ??
#              - s
#
#        provider:
#          google:
#            authorization-uri: ??? ??? ? ??
#            token-uri: ?? ?? ?? ??
#            user-info-uri: ??? ?? ?? ??
#            user-name-attribute: ?? ??? ??
#          naver:
#            authorization-uri: ??? ??? ? ??
#            token-uri: ?? ?? ?? ??
#            user-info-uri: ??? ?? ?? ??
#            user-name-attribute: ?? ??? ??

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10011/auth
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: dkssudgktpdydlrjtdmsjwttlzmfltzldlqslek
